version: "3"
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        working_dir: /var/www/jumia_phonebook
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/jumia_phonebook
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./storage/logs/jumia_phonebook:/storage/logs/jumia_phonebook
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        working_dir: /var/www/jumia_phonebook
        environment:
            - NGINX_HOST=jumia_phonebook.local
        volumes:
            - ./:/var/www/jumia_phonebook
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
            - ./storage/logs/nginx/:/storage/logs/nginx/
        links:
            - php
